services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: 
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      -pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: